Updated the deploy.yml file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,6 +25,13 @@ jobs:
         run: |
           cp README.md content
           jupyter lite build --contents content --output-dir dist
+      - name: List files
+        run: ls -R  
+
+      - name: Run Script
+        run: |
+          python ./script.py || { echo 'Script failed'; }
+          
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
@@ -43,13 +50,6 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
-      - name: List files
-        run: ls -R  
-
-      - name: Run Script
-        run: |
-          python ./script.py || { echo 'Script failed'; }
-
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
